# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'firstgui.ui'
#
# Created by: PyQt5 UI code generator 5.10.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(970, 820)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.audio1 = QtWidgets.QPushButton(self.centralwidget)
        self.audio1.setGeometry(QtCore.QRect(72, 50, 141, 41))
        self.audio1.setObjectName("audio1")
        self.audio2 = QtWidgets.QPushButton(self.centralwidget)
        self.audio2.setGeometry(QtCore.QRect(72, 130, 141, 41))
        self.audio2.setObjectName("audio2")
        self.compare = QtWidgets.QPushButton(self.centralwidget)
        self.compare.setGeometry(QtCore.QRect(100, 280, 111, 41))
        self.compare.setObjectName("compare")
        self.percentage_slider = QtWidgets.QSlider(self.centralwidget)
        self.percentage_slider.setGeometry(QtCore.QRect(180, 190, 401, 31))
        self.percentage_slider.setMaximum(100)
        self.percentage_slider.setOrientation(QtCore.Qt.Horizontal)
        self.percentage_slider.setObjectName("percentage_slider")
        self.mix = QtWidgets.QPushButton(self.centralwidget)
        self.mix.setGeometry(QtCore.QRect(340, 260, 93, 28))
        self.mix.setObjectName("mix")
        self.average = QtWidgets.QRadioButton(self.centralwidget)
        self.average.setGeometry(QtCore.QRect(590, 50, 95, 20))
        self.average.setObjectName("average")
        self.perception = QtWidgets.QRadioButton(self.centralwidget)
        self.perception.setGeometry(QtCore.QRect(590, 90, 95, 20))
        self.perception.setObjectName("perception")
        self.difference = QtWidgets.QRadioButton(self.centralwidget)
        self.difference.setGeometry(QtCore.QRect(590, 130, 95, 20))
        self.difference.setObjectName("difference")
        self.tableWidget = QtWidgets.QTableWidget(self.centralwidget)
        self.tableWidget.setGeometry(QtCore.QRect(280, 340, 311, 431))
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(2)
        self.tableWidget.setRowCount(10)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(6, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(7, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(8, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(9, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(1, item)
        self.lineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit.setGeometry(QtCore.QRect(250, 50, 291, 31))
        self.lineEdit.setObjectName("lineEdit")
        self.lineEdit_2 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_2.setGeometry(QtCore.QRect(250, 130, 291, 31))
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.percentage_label = QtWidgets.QLabel(self.centralwidget)
        self.percentage_label.setGeometry(QtCore.QRect(210, 220, 67, 17))
        self.percentage_label.setObjectName("percentage_label")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 970, 22))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.percentage_slider.sliderMoved['int'].connect(self.percentage_label.setNum)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.audio1.setText(_translate("MainWindow", "Browse_Audio_1"))
        self.audio2.setText(_translate("MainWindow", "Browse_Audio_2"))
        self.compare.setText(_translate("MainWindow", "Compare"))
        self.mix.setText(_translate("MainWindow", "MIX"))
        self.average.setText(_translate("MainWindow", "Average"))
        self.perception.setText(_translate("MainWindow", "Perception"))
        self.difference.setText(_translate("MainWindow", "Difference"))
        item = self.tableWidget.verticalHeaderItem(0)
        item.setText(_translate("MainWindow", "Row1"))
        item = self.tableWidget.verticalHeaderItem(1)
        item.setText(_translate("MainWindow", "Row2"))
        item = self.tableWidget.verticalHeaderItem(2)
        item.setText(_translate("MainWindow", "Row3"))
        item = self.tableWidget.verticalHeaderItem(3)
        item.setText(_translate("MainWindow", "Row4"))
        item = self.tableWidget.verticalHeaderItem(4)
        item.setText(_translate("MainWindow", "Row5"))
        item = self.tableWidget.verticalHeaderItem(5)
        item.setText(_translate("MainWindow", "Row6"))
        item = self.tableWidget.verticalHeaderItem(6)
        item.setText(_translate("MainWindow", "Row7"))
        item = self.tableWidget.verticalHeaderItem(7)
        item.setText(_translate("MainWindow", "Row8"))
        item = self.tableWidget.verticalHeaderItem(8)
        item.setText(_translate("MainWindow", "Row9"))
        item = self.tableWidget.verticalHeaderItem(9)
        item.setText(_translate("MainWindow", "Row10"))
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "column1"))
        item = self.tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "column2"))
        self.percentage_label.setText(_translate("MainWindow", "0"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

